version: '3'
services:
  go-api1:
      container_name: go-api1 
      #image: allancordeiros/rinha-go:latest
      build: .        
      hostname: go-api1              
      depends_on:
        - db          
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '1.0GB'
      networks:
        - rinha-go-nw
  go-api2:
      container_name: go-api2 
      #image: allancordeiros/rinha-go:latest
      build: .
      hostname: go-api2              
      depends_on:
        - db          
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '1.0GB'
      networks:
        - rinha-go-nw
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - go-api1
      - go-api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'
    networks:
      - rinha-go-nw
  db:
    image: postgres:15.2-alpine
    volumes:
      - .data:/var/lib/postgresql/data
      - ./sql:/migrations
    command: postgres -c 'max_connections=200'    
    tty: true
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinhadb    
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s    
      resources:
        limits:
          cpus: '0.9'
          memory: '0.8GB'  
    networks:
      - rinha-go-nw
  db-schema-check:
    image: postgres:15.2-alpine
    restart: no
    volumes:
      - ./sql:/migrations    
    entrypoint: [ "sh", "-c", "chmod +x /migrations/validate_migrations.sh && /migrations/validate_migrations.sh" ]
    depends_on:
      - db
    networks:
      - rinha-go-nw
networks:
  rinha-go-nw:

# https://www.enterprisedb.com/postgres-tutorials/introduction-postgresql-performance-tuning-and-optimization